- name: CIS - Ensure Password Minimum Length Is Configured (Fleetd Required)
  platform: darwin
  description: |
    A minimum password length is the fewest number of characters a password can contain to meet a system's requirements. Ensure that a minimum of a 15-character password is part of the password policy on the computer.
  resolution: |
    Profile Method:
    Create or edit a configuration profile with the following information:
      - PayloadType: com.apple.mobiledevice.passwordpolicy
      - Key: minLength
      - Value: <integer>15</integer> (or any value ≥ 15)
  query: |
    SELECT 1 FROM (
      SELECT CAST(JSON_EXTRACT(policy_parameters, '$.minimumLength') AS INTEGER) AS minlength
      FROM password_policy
      WHERE policy_identifier LIKE '%minChars'
      AND minlength >= 15
    );
