apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure Install Security Responses and System Files Is Enabled (MDM Required)
  query: |
    SELECT 1 WHERE
      EXISTS (
        SELECT 1 FROM managed_policies WHERE
          domain='com.apple.SoftwareUpdate' AND
          name='ConfigDataInstall' AND
          (value = 1 OR value = 'true') AND
          username = ''
      )
      AND NOT EXISTS (
        SELECT 1 FROM managed_policies WHERE
          domain='com.apple.SoftwareUpdate' AND
          name='ConfigDataInstall' AND
          (value != 1 AND value != 'true')
      )
      AND EXISTS (
        SELECT 1 FROM managed_policies WHERE
          domain='com.apple.SoftwareUpdate' AND
          name='CriticalUpdateInstall' AND
          (value = 1 OR value = 'true') AND
          username = ''
      )
      AND NOT EXISTS (
        SELECT 1 FROM managed_policies WHERE
          domain='com.apple.SoftwareUpdate' AND
          name='CriticalUpdateInstall' AND
          (value != 1 AND value != 'true')
      );
  critical: false
  description: |
    Ensure that system and security updates are installed after they are available from Apple. This setting enables definition updates for XProtect and Gatekeeper. With this setting in place, new malware and adware that Apple has added to the list of malware or untrusted software will not execute. These updates do not require reboots or end user admin rights.

    Apple has introduced a security feature that allows for smaller downloads and the installation of security updates when a reboot is not required. This feature is only available when the last regular update has already been applied. This feature emphasizes that a Mac must be up-to-date on patches so that Apple's security tools can be used to quickly patch when a rapid response is necessary.
  resolution: |
    Graphical Method:
      1. Open System Settings
      2. Select General
      3. Select Software Update
      4. Select the i
      5. Set Install Security Responses and System files to enabled
      6. Select Done

    Profile Method:
    Create or edit a configuration profile with the following information:
      - PayloadType: com.apple.SoftwareUpdate
      - Key: ConfigDataInstall, Value: <true/>
      - Key: CriticalUpdateInstall, Value: <true/>
  platform: darwin
