apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure Guest Account Is Disabled
  query: |
    SELECT 1 WHERE
      EXISTS (
        SELECT 1 FROM plist WHERE
          path = '/Library/Preferences/com.apple.loginwindow.plist' AND
          key = 'GuestEnabled' AND
          value = 0
      )
      OR (
        EXISTS (
          SELECT 1 FROM managed_policies WHERE
            domain = 'com.apple.MCX' AND
            name = 'DisableGuestAccount' AND
            (value = 1 OR value = 'true') AND
            username = ''
        )
        AND EXISTS (
          SELECT 1 FROM managed_policies WHERE
            domain = 'com.apple.MCX' AND
            name = 'EnableGuestAccount' AND
            (value = 0 OR value = 'false') AND
            username = ''
        )
      );
  critical: false
  description: The guest account allows users access to the system without having to create an account or password. Disabling the guest account mitigates the risk of an untrusted user doing basic reconnaissance and possibly using privilege escalation attacks to take control of the system.
  resolution: |
    Graphical Method:
      1. Open System Settings
      2. Select Users & Groups
      3. Select the i next to the Guest User
      4. Set Allow guests to log in to this computer to disabled
    
    Terminal Method:
      /usr/bin/sudo /usr/bin/defaults write /Library/Preferences/com.apple.loginwindow GuestEnabled -bool false
    
    Profile Method:
    Create or edit a configuration profile with the following information:
      - PayloadType: com.apple.MCX
      - Key: DisableGuestAccount, Value: <true/>
      - Key: EnableGuestAccount, Value: <false/>
  platform: darwin
