apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure Screen Saver Hot Corners Are Secure For Current User (FDA Required)
  query: |
    SELECT 1 WHERE NOT EXISTS (
      SELECT 1 FROM plist
      WHERE path = (
          SELECT '/Users/' || user || '/Library/Preferences/com.apple.dock.plist'
          FROM logged_in_users
          WHERE type = 'user' AND tty = 'console'
          ORDER BY time DESC
          LIMIT 1
        )
        AND key IN ('wvous-tl-corner', 'wvous-tr-corner', 'wvous-bl-corner', 'wvous-br-corner')
        AND value = 6
    );
  critical: false
  description: |
    Hot Corners can be configured to disable the screen saver by moving the mouse cursor to a corner of the screen. This can only be accomplished by the current user, so that is the only user that needs to be audited. Setting a hot corner to disable the screen saver poses a potential security risk since an unauthorized person could use this to bypass the login screen and gain access to the system.

    FDA (Full Disk Access) is required to read the current console user's Dock configuration (`/Users/<current user>/Library/Preferences/com.apple.dock.plist`).
  resolution: |
    Graphical Method:
      1. Open System Settings
      2. Select Desktop & Dock
      3. Select Hot Corners...
      4. Verify that Disable Screen Saver (value 6) is not set to any of the corners

    Terminal Method (current user):
      /usr/bin/sudo -u <current user> /usr/bin/defaults write com.apple.dock wvous-tl-corner -int 0
      /usr/bin/sudo -u <current user> /usr/bin/defaults write com.apple.dock wvous-tr-corner -int 0
      /usr/bin/sudo -u <current user> /usr/bin/defaults write com.apple.dock wvous-bl-corner -int 0
      /usr/bin/sudo -u <current user> /usr/bin/defaults write com.apple.dock wvous-br-corner -int 0
  platform: darwin
