apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure Advertising Privacy Protection in Safari Is Enabled (MDM Required)
  query: |
    SELECT 1 WHERE
      EXISTS (
        SELECT 1 FROM managed_policies WHERE
          domain = 'com.apple.Safari' AND
          name = 'WebKitPreferences.privateClickMeasurementEnabled' AND
          (value = 1 OR value = 'true')
      )
      AND NOT EXISTS (
        SELECT 1 FROM managed_policies WHERE
          domain = 'com.apple.Safari' AND
          name = 'WebKitPreferences.privateClickMeasurementEnabled' AND
          (value != 1 AND value != 'true')
      );
  critical: false
  description: |
    Apple provides a framework that allows advertisers to target Apple users with advertisements. Organizations should manage user privacy settings on managed devices to align with organizational policies and user data protection requirements. Private click measurement is the privacy-preserving mechanism for ad-click attribution.
  resolution: |
    Profile Method:
    Create or edit a configuration profile with the following information:
      - PayloadType: com.apple.Safari
      - Key: WebKitPreferences.privateClickMeasurementEnabled
      - Value: <true/>
  platform: darwin
