apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure Show Password Hints Is Disabled
  query: SELECT 1 FROM plist WHERE path = '/Library/Preferences/com.apple.loginwindow.plist' AND key = 'RetriesUntilHint' AND value = 0;
  critical: false
  description: |
    Password hints are user-created text displayed when an incorrect password is used for an account. Password hints make it easier for unauthorized persons to gain access to systems by displaying information provided by the user to assist in remembering the password. This information could include the password itself or other information that might be readily discerned with basic knowledge of the end user.

    In macOS 26 Tahoe, setting RetriesUntilHint to a value other than 0 will result in the hint question mark icon appearing in the login window. Setting this to 0 is the only definitive way to ensure that does not appear.
  resolution: |
    Graphical Method:
      1. Open System Settings
      2. Select Lock Screen
      3. Set 'Show password hints' to disabled

    Terminal Method:
      /usr/bin/sudo /usr/bin/defaults write /Library/Preferences/com.apple.loginwindow RetriesUntilHint -int 0

    Profile Method:
    Create or edit a configuration profile with the following information:
      - PayloadType: com.apple.loginwindow
      - Key: RetriesUntilHint
      - Value: <integer>0</integer>
  platform: darwin
