apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure AirDrop Is Disabled When Not Actively Transferring Files (MDM Required)
  query: |
    SELECT 1 WHERE
      EXISTS (
        SELECT 1 FROM managed_policies WHERE
          domain='com.apple.applicationaccess' AND
          name='allowAirDrop' AND
          (value = 0 OR value = 'false') AND
          username = ''
      )
      AND NOT EXISTS (
        SELECT 1 FROM managed_policies WHERE
          domain='com.apple.applicationaccess' AND
          name='allowAirDrop' AND
          (value != 0 AND value != 'false')
      );
  critical: false
  description: |
    AirDrop is Apple's built-in, on-demand, ad hoc file exchange system that is compatible with both macOS and iOS. It uses Bluetooth LE for discovery that limits connectivity to Mac or iOS users that are in close proximity. Depending on the setting, it allows everyone or only Contacts to share files when they are near each other.

    While there are positives to AirDrop, there are privacy concerns that could expose personal information. For that reason, AirDrop should be disabled, and should only be enabled when needed and disabled afterwards.

    Note: AirDrop can only be enabled or disabled through configuration profiles. If your organization wants to use AirDrop, it would need to be set through Terminal or the GUI.
  resolution: |
    Profile Method:
    Create or edit a configuration profile with the following information:
      - PayloadType: com.apple.applicationaccess
      - Key: allowAirDrop, Value: <false/>
  platform: darwin
