apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Show Location Icon in Control Center when System Services Request Your Location' Is Enabled
  query: SELECT 1 FROM plist WHERE path = '/Library/Preferences/com.apple.locationmenu.plist' AND key = 'ShowSystemServices' AND value = 1;
  critical: false
  description: This setting provides the user an understanding of the current status of Location Services and which applications are using it. Enabling the "Show location icon in the menu bar when System Services request your location" setting will show an arrow in the control center when a system service accesses the location.
  resolution: |
    Graphical Method:
      1. Open System Settings
      2. Select Privacy & Security
      3. Select Location Services
      4. Select Details...
      5. Set Show location icon in menu bar when System Services request your location to enabled
    
    Terminal Method:
      /usr/bin/sudo /usr/bin/defaults write /Library/Preferences/com.apple.locationmenu.plist ShowSystemServices -bool true
  platform: darwin
