apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure Show Full Website Address in Safari Is Enabled (MDM Required)
  query: |
    SELECT 1 WHERE
      EXISTS (
        SELECT 1 FROM managed_policies WHERE
          domain = 'com.apple.Safari' AND
          name = 'ShowFullURLInSmartSearchField' AND
          (value = 1 OR value = 'true')
      )
      AND NOT EXISTS (
        SELECT 1 FROM managed_policies WHERE
          domain = 'com.apple.Safari' AND
          name = 'ShowFullURLInSmartSearchField' AND
          (value != 1 AND value != 'true')
      );
  critical: false
  description: Attackers use websites with malicious or unwanted content to exploit the user or the computer. Full visibility into what site is being visited is important for privacy and security — the full website address should always be displayed in Safari.
  resolution: |
    Profile Method:
    Create or edit a configuration profile with the following information:
      - PayloadType: com.apple.Safari
      - Key: ShowFullURLInSmartSearchField
      - Value: <true/>
  platform: darwin
