- name: |
    CIS - Ensure 'Configure password backup directory' is set to 'Enabled: Active Directory' or 'Enabled: Azure Active Directory'
  platform: windows
  description: |
    This policy setting configures which directory Windows LAPS will use to back up the local admin account password.
    The recommended state for this setting is: Enabled: Active Directory or Enabled: Azure Active Directory.
    Note: Organizations that utilize third-party commercial software to manage unique & complex local Administrator passwords on domain members may opt to disregard these LAPS recommendations.
    Note #2: Windows LAPS does not support standalone computers - they must be joined to an Active Directory domain or Entra ID (formerly Azure Active Directory).
    Note #3: Windows LAPS does not support simultaneous storage of the local admin password in both directory types.
    Note #4: If the setting is configured and the managed device is not joined to the configured directory type, the local administrator password will not be managed by Windows LAPS.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Enabled: Active Directory or Enabled: Azure Active Directory:
    'Computer Configuration\Policies\Administrative Templates\System\LAPS\Configure password backup directory'
  query: |
    SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\LAPS\BackupDirectory' AND data in (1, 2));
