- name: CIS - Ensure 'Allow a Windows app to share application data between users' is set to 'Disabled'
  platform: windows
  description: |
    This policy manages a Windows app's ability to share data between users who have installed the
    app. Data is shared through the SharedLocal folder. This folder is available through the
    Windows.Storage API.
  resolution: |
    Automatic method:
    Ask your system administrator to establish the recommended configuration via GP, set the following UI path to 'Disabled':
    'Computer Configuration\Policies\Administrative Templates\Windows Components\App Package Deployment\Allow a Windows app to share application data between users'
  query: |
    SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\CurrentVersion\\AppModel\\StateManager\\AllowSharedLocalAppData' AND data == 0);
