- name: CIS - Ensure 'Configure RPC connection settings - Use authentication for outgoing RPC connections' is set to 'Enabled to Default'
  platform: windows
  description: |-
    This policy setting controls which protocol and protocol settings to use for outgoing
    Remote Procedure Call (RPC) connections to a remote print spooler.
    The recommended state for this setting is: Enabled: Default
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled: Default:
    Administrative Templates\Printers\Configure RPC connection settings: Use
    authentication for outgoing RPC connections
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Rpc\RpcAuthentication' AND data = '1';
