- name: 'CIS - Ensure ''Password Age Days'' is set to ''Configured: 30 or fewer'''
  platform: windows
  description: |-
    This policy setting configures the Windows LAPS Password Settings policy for
    password age.
    Because attackers can crack passwords, the more frequently the password is changed
    the less opportunity an attacker has to use a cracked password.
    The recommended state for this setting is: Configured: 30 or fewer.
    Note: Organizations that utilize third-party commercial software to manage unique &
    complex local Administrator passwords on domain members may opt to disregard these
    LAPS recommendations.
    Note #2: Windows LAPS does not support standalone computers - they must be joined
    to an Active Directory domain or Entra ID (formerly Azure Active Directory).
  resolution: |-
    To establish the recommended configuration from Microsoft Intune Admin Center:
    1. Navigate to Endpoint security > Account protection.
    2. Create or edit a LAPS policy type Local admin password solution (Windows
    LAPS).
    3. Set Password Age Days to Configured: 30 (or fewer)
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/ADMX_AdmPwd/POL_AdmPwd</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%<enabled%' AND CAST(SUBSTR(mdm_command_output, INSTR(mdm_command_output, 'ELM_AdmPwd_PasswordAgeDays" value="') + 35, 2) AS INTEGER) BETWEEN 1 AND 30;
