- name: 'CIS - Ensure ''Configure RPC connection settings: Protocol to use for outgoing RPC connections'' is set to ''Enabled: RPC over TCP'''
  platform: windows
  description: |-
    This policy setting controls which protocol and protocol settings to use for outgoing
    Remote Procedure Call (RPC) connections to a remote print spooler.
    The recommended state for this setting is: Enabled: RPC over TCP
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled: RPC over TCP:
    Administrative Templates\Printers\Configure RPC connection settings: Protocol
    to use for outgoing RPC connections
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/Printers/ConfigureRpcConnectionPolicy</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%RpcConnectionProtocol_Enum" value="0"%';
