- name: 'CIS - Ensure ''Configure Windows Defender SmartScreen'' is set to ''Enabled: Warn and prevent bypass'''
  platform: windows
  description: |-
    This policy setting allows you to manage the behavior of Windows Defender
    SmartScreen. Windows Defender SmartScreen helps keep PCs safer by warning users
    before running unrecognized programs downloaded from the Internet. Some information
    is sent to Microsoft about files and programs run on PCs with this feature enabled.
    The recommended state for this setting is: Enabled: Warn and prevent bypass.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled: Warn and prevent bypass.
    Administrative Templates\Windows Components\File Explorer\Configure Windows
    Defender SmartScreen
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System\EnableSmartScreen' AND data = '1';
