apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Allow Email Scanning' is set to 'Allowed'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/Defender/AllowEmailScanning</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '1';
  critical: false
  description: |
    This policy setting allows you to configure e-mail scanning. When e-mail scanning is
    enabled, the engine will parse the mailbox and mail files, according to their specific
    format, in order to analyze the mail bodies and attachments. Several e-mail formats are
    currently supported, for example: pst (Outlook), dbx, mbx, mime (Outlook Express),
    binhex (Mac).
    The recommended state for this setting is: Allowed.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Allowed.
    Defender\Allow Email Scanning
  platform: windows
