apiVersion: v1
kind: policy
spec:
  name: 'CIS - Ensure ''Point and Print Restrictions: When installing drivers for a new connection'' is set to ''Enabled: Show warning and elevation prompt'''
  query: SELECT 1 FROM registry WHERE path LIKE 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\Providers\%\default\Device\Printers\PointAndPrintRestrictions' AND data LIKE '%PointAndPrint_NoWarningNoElevationOnInstall_Enum" value="0"%';
  critical: false
  description: |-
    This policy setting controls whether computers will show a warning and a security
    elevation prompt when users create a new printer connection using Point and Print.
    The recommended state for this setting is: Enabled: Show warning and elevation
    prompt.
    Note: On August 10, 2021, Microsoft announced a Point and Print Default Behavior
    Change which modifies the default Point and Print driver installation and update
    behavior to require Administrator privileges. This is documented in KB5005652—
    Manage new Point and Print default driver installation behavior (CVE-2021-34481). This
    change overrides all Point and Print Group Policy settings and ensures that only
    Administrators can install printer drivers from a print server using Point and Print.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled: Show warning and elevation prompt.
    Administrative Templates\Printers\Point and Print Restrictions: When
    installing drivers for a new connection
  platform: windows
