apiVersion: v1
kind: policy
spec:
  name: "CIS - Ensure 'Microsoft network client: Send unencrypted password to third-party SMB servers' is set to 'Disabled'"
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters\EnablePlainTextPassword' AND data = '0';
  critical: false
  description: |
    This policy setting determines whether the SMB redirector will send plaintext passwords
    during authentication to third-party SMB servers that do not support password
    encryption.
    It is recommended that you disable this policy setting unless there is a strong business
    case to enable it. If this policy setting is enabled, unencrypted passwords will be allowed
    across the network.
    The recommended state for this setting is: Disabled.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Disabled:
    Local Policies Security Options\Microsoft network client: Send unencrypted
    password to third-party SMB servers
  platform: windows
