apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Microsoft iSCSI Initiator Service (MSiSCSI)' is set to 'Disabled'
  query: SELECT 1 FROM services WHERE name = 'MSiSCSI' AND UPPER(start_type) = 'DISABLED';
  critical: false
  description: 'Manages Internet SCSI (iSCSI) sessions from this computer to remote target devices. The recommended state for this setting is: Disabled.'
  resolution: 'Remediation of this service is currently not possible through Settings Catalog or a custom profile OMA-URI. Instead, it can be scripted and deployed through the Intune Scripts or Remediations blade or by other means. To establish the recommended configuration via PowerShell, run the following cmdlet: Set-Service -Name MSiSCSI -StartupType Disabled'
  platform: windows
