apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'MSI Allow user control over installs' is set to 'Disabled'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/ApplicationManagement/MSIAllowUserControlOverInstall</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '0';
  critical: false
  description: |-
    This setting controls whether users are permitted to change installation options that
    typically are available only to system administrators. The security features of Windows
    Installer normally prevent users from changing installation options that are typically
    reserved for system administrators, such as specifying the directory to which files are
    installed. If Windows Installer detects that an installation package has permitted the
    user to change a protected option, it stops the installation and displays a message.
    These security features operate only when the installation program is running in a
    privileged security context in which it has access to directories denied to the user.
    The recommended state for this setting is: Disabled.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Disabled:
    Microsoft App Store\MSI Allow user control over installs
  platform: windows
