apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Enable Virtualization Based Security' is set to 'Enable virtualization based security'
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard\EnableVirtualizationBasedSecurity' AND data = '1';
  critical: false
  description: |
    This policy setting specifies whether Virtualization Based Security is enabled.
    Virtualization Based Security uses the Windows Hypervisor to provide support for
    security services.
    The recommended state for this setting is: Enable virtualization based security.
    Note: Virtualization Based Security requires a 64-bit version of Windows with Secure
    Boot enabled, which in turn requires that Windows was installed with a UEFI BIOS
    configuration, not a Legacy BIOS configuration. In addition, if running Windows on a
    virtual machine, the hardware-assisted CPU virtualization feature (Intel VT-x or AMD-V)
    must be exposed by the host to the guest VM.
    More information on system requirements for this feature can be found at Windows
    Defender Credential Guard Requirements (Windows 10) | Microsoft Docs
    Note #2: Credential Guard and Device Guard are not currently supported when using
    Azure IaaS VMs.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enable virtualization based security:
    Device Guard\Enable Virtualization Based Security
  platform: windows
