apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Account Logon Audit Credential Validation' is set to 'Success and Failure'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/Audit/AccountLogon_AuditCredentialValidation</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '3';
  critical: false
  description: |
    This subcategory reports the results of validation tests on credentials submitted for a
    user account logon request. These events occur on the computer that is authoritative for
    the credentials. For domain accounts, the Domain Controller is authoritative, whereas
    for local accounts, the local computer is authoritative. In domain environments, most of
    the Account Logon events occur in the Security log of the Domain Controllers that are
    authoritative for the domain accounts. However, these events can occur on other
    computers in the organization when local accounts are used to log on. Events for this
    subcategory include:
    •
    •
    •
    •
    
    4774: An account was mapped for logon.
    4775: An account could not be mapped for logon.
    4776: The Domain Controller attempted to validate the credentials for an
    account.
    4777: The Domain Controller failed to validate the credentials for an account.
    
    The recommended state for this setting is: Success and Failure.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Success and Failure.
    Auditing\Account Logon Audit Credential Validation
  platform: windows
