apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Require a password when a computer wakes (plugged in)' is set to 'Enabled'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/Power/RequirePasswordWhenComputerWakesPluggedIn</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%<enabled%';
  critical: false
  description: |
    Specifies whether or not the user is prompted for a password when the system resumes
    from sleep.
    The recommended state for this setting is: Enabled.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled.
    Administrative Templates\System\Power Management\Sleep Settings\Require a
    password when a computer wakes (plugged in)
  platform: windows
