apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Always prompt for password upon connection' is set to 'Enabled'
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\fPromptForPassword' AND data = '1';
  critical: false
  description: |-
    This policy setting specifies whether Remote Desktop Services always prompts the
    client computer for a password upon connection. You can use this policy setting to
    enforce a password prompt for users who log on to Remote Desktop Services, even if
    they already provided the password in the Remote Desktop Connection client.
    The recommended state for this setting is: Enabled.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled.
    Administrative Templates\Windows Components\Remote Desktop Services\Remote
    Desktop Session Host\Security\Always prompt for password upon connection
  platform: windows
