apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Prevent device metadata retrieval from the Internet' is set to 'Enabled'
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Device Metadata\PreventDeviceMetadataFromNetwork' AND data = '1';
  critical: false
  description: |
    This policy setting allows you to prevent Windows from retrieving device metadata from
    the Internet.
    The recommended state for this setting is: Enabled.
    Note: This will not prevent the installation of basic hardware drivers, but does prevent
    associated third-party utility software from automatically being installed under the
    context of the SYSTEM account.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled.
    Administrative Templates\System\Device Installation\Prevent device metadata
    retrieval from the Internet
  platform: windows
