apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Enable App Installer Experimental Features' is set to 'Disabled'
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\AppInstaller\EnableExperimentalFeatures' AND data = '0';
  critical: false
  description: |-
    This policy setting controls whether users can enable experimental features in the
    Windows Package Manager.
    The recommended state for this setting is Disabled.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Disabled:
    Administrative Templates\Windows Components\Desktop App Installer\Enable App
    Installer Experimental Features
  platform: windows
