apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Microsoft FTP Service (FTPSVC)' is set to 'Disabled' or 'Not Installed'
  query: SELECT 1 WHERE COALESCE((SELECT UPPER(start_type) FROM services WHERE name = 'FTPSVC'), 'DISABLED') = 'DISABLED';
  critical: false
  description: |-
    Enables the server to be a File Transfer Protocol (FTP) server.
    The recommended state for this setting is: Disabled or Not Installed.
    Note: This service is not installed by default. It is supplied with Windows, but is installed
    by enabling an optional Windows feature (Internet Information Services - FTP Server).
  resolution: |-
    To establish the recommended configuration, set the following Custom Configuration
    Policy to 4 or confirm that the service is Not installed:
    Name:
    <Enter name>
    Description: <Enter Description>
    OMA-URI:
    ./Device/Vendor/MSFT/Policy/Config/SystemServices/ConfigureMicrosoftFTPServic
    eStartupMode
    Data Type:
    Integer
    Value:
    4

    Note: As of January 2024, despite its inclusion in Microsoft’s official documentation,
    using an OMI-URI to configure a Windows Service Startup Mode via a custom profile
    will lead to an error in Intune. This error will be logged in the local event log as “The
    system cannot find the file specified.” Currently, the most reliable method for
    remediation is through PowerShell.
    The recommended configuration can also be established via PowerShell by running the
    following cmdlet:
    Set-Service -Name FTPSVC -StartupType Disabled
  platform: windows
