apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'LxssManager (LxssManager)' is set to 'Disabled' or 'Not Installed'
  query: SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM services WHERE name = 'LxssManager') OR EXISTS (SELECT 1 FROM services WHERE name = 'LxssManager' AND start_type = 'DISABLED');
  critical: false
  description: |
    The LXSS Manager service supports running native ELF binaries. The service provides
    the infrastructure necessary for ELF binaries to run on Windows.
    The recommended state for this setting is: Disabled or Not Installed.
    Note: This service is not installed by default. It is supplied with Windows, but is installed
    by enabling an optional Windows feature (Windows Subsystem for Linux).
  resolution: |
    To establish the recommended configuration, set the following Custom Configuration
    Policy to 4 or confirm that the service is Not installed:
    Name:
    <Enter name>
    Description: <Enter Description>
    OMA-URI:
    ./Device/Vendor/MSFT/Policy/Config/SystemServices/ConfigureLxssManagerService
    StartupMode
    Data Type:
    Integer
    Value:
    4
    
    Note: As of January 2024, despite its inclusion in Microsoft’s official documentation,
    using an OMI-URI to configure a Windows Service Startup Mode via a custom profile
    will lead to an error in Intune. This error will be logged in the local event log as “The
    system cannot find the file specified.” Currently, the most reliable method for
    remediation is through PowerShell.
    The recommended configuration can also be established via PowerShell by running the
    following cmdlet:
    Set-Service -Name LxssManager -StartupType Disabled
  platform: windows
