apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Xbox Live Auth Manager (XblAuthManager)' is set to 'Disabled'
  query: SELECT 1 WHERE COALESCE((SELECT UPPER(start_type) FROM services WHERE name = 'XblAuthManager'), 'DISABLED') = 'DISABLED';
  critical: false
  description: |
    Provides authentication and authorization services for interacting with Xbox Live.
    The recommended state for this setting is: Disabled.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Disabled.
    System Services\Xbox Live Auth Manager
  platform: windows
