apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Remote Procedure Call (RPC) Locator (RpcLocator)' is set to 'Disabled'
  query: SELECT 1 WHERE COALESCE((SELECT UPPER(start_type) FROM services WHERE name = 'RpcLocator'), 'DISABLED') = 'DISABLED';
  critical: false
  description: |-
    In Windows 2003 and older versions of Windows, the Remote Procedure Call (RPC)
    Locator service manages the RPC name service database. In Windows Vista or newer
    versions of Windows, this service does not provide any functionality and is present for
    application compatibility.
    The recommended state for this setting is: Disabled.
  resolution: |-
    To establish the recommended configuration, set the following Custom Configuration
    Policy to 4:
    Name:
    <Enter name>
    Description: <Enter Description>
    OMA-URI:
    ./Device/Vendor/MSFT/Policy/Config/SystemServices/ConfigureRemoteProcedureCal
    lLocatorServiceStartupMode
    Data Type:
    Integer
    Value:
    4

    Note: As of January 2024, despite its inclusion in Microsoft’s official documentation,
    using an OMI-URI to configure a Windows Service Startup Mode via a custom profile
    will lead to an error in Intune. This error will be logged in the local event log as “The
    system cannot find the file specified.” Currently, the most reliable method for
    remediation is through PowerShell.
    The recommended configuration can also be established via PowerShell by running the
    following cmdlet:
    Set-Service -Name RpcLocator -StartupType Disabled
  platform: windows
