apiVersion: v1
kind: policy
spec:
  name: "CIS - Ensure 'Password Length' is set to 'Configured: 15 or more'"
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/ADMX_AdmPwd/POL_AdmPwd</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%<enabled%' AND CAST(SUBSTR(mdm_command_output, INSTR(mdm_command_output, 'ELM_AdmPwd_PasswordLength" value="') + 34, 2) AS INTEGER) >= 15;
  critical: false
  description: |
    This policy setting configures the Windows LAPS Password Settings policy for
    password length.
    Each additional character in a password increases its complexity exponentially. For
    instance, a seven-character, all lower-case alphabetic password would have 26 to the
    power of 7 (approximately 8 x 10 to the power of 9 or 8 billion) possible combinations.
    At 1,000,000 attempts per second (a capability of many password-cracking utilities), it
    would only take 133 minutes to crack. A seven-character alphabetic password with case
    sensitivity has 52 to the power of 7 combinations. A seven-character case-sensitive
    alphanumeric password without punctuation has 627 combinations. An eight-character
    password has 26 to the power of 8 (or 2 x 10 to the power of 11) possible combinations.
    Although this might seem to be a large number, at 1,000,000 attempts per second it
    would take only 59 hours to try all possible passwords. Remember, these times will
    significantly increase for passwords that use ALT characters and other special keyboard
    characters such as "!" or "@". Proper use of the password settings can help make it
    difficult to mount a brute force attack.
    The recommended state for this setting is: Configured: 15 or more.
    Note: Organizations that utilize third-party commercial software to manage unique &
    complex local Administrator passwords on domain members may opt to disregard these
    LAPS recommendations.
    Note #2: Windows LAPS does not support standalone computers - they must be joined
    to an Active Directory domain or Entra ID (formerly Azure Active Directory).
  resolution: |
    To establish the recommended configuration from Microsoft Intune Admin Center:
    1. Navigate to Endpoint security > Account protection.
    2. Create or edit a LAPS policy type Local admin password solution (Windows
    LAPS).
    3. Set Password Length to Configured: 15 (or more).
  platform: windows
