apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Remote host allows delegation of nonexportable credentials' is set to 'Enabled'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/CredentialsDelegation/RemoteHostAllowsDelegationOfNonExportableCredentials</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%<Enabled/>%';
  critical: false
  description: |-
    Remote host allows delegation of non-exportable credentials. When using credential
    delegation, devices provide an exportable version of credentials to the remote host. This
    exposes users to the risk of credential theft from attackers on the remote host. The
    Restricted Admin Mode and Windows Defender Remote Credential Guard features are
    two options to help protect against this risk.
    The recommended state for this setting is: Enabled.
    Note: More detailed information on Windows Defender Remote Credential Guard and
    how it compares to Restricted Admin Mode can be found at this link: Protect Remote
    Desktop credentials with Windows Defender Remote Credential Guard (Windows 10) |
    Microsoft Docs
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled.
    Administrative Templates\System\Credentials Delegation\Remote host allows
    delegation of non-exportable credentials
  platform: windows
