apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Continue experiences on this device' is set to 'Disabled'
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System\EnableCdp' AND data = '0';
  critical: false
  description: |-
    This policy setting determines whether the Windows device is allowed to participate in
    cross-device experiences (continue experiences).
    The recommended state for this setting is: Disabled.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Disabled.
    Administrative Templates\System\Group Policy\Continue experiences on this
    device
  platform: windows
