apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Modify Firmware Environment' is set to 'Administrators'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/UserRights/ModifyFirmwareEnvironment</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%Administrators%';
  critical: false
  description: |
    This policy setting allows users to configure the system-wide environment variables that
    affect hardware configuration. This information is typically stored in the Last Known
    Good Configuration. Modification of these values and could lead to a hardware failure
    that would result in a denial of service condition.
    The recommended state for this setting is: *S-1-5-32-544 (Administrators).
    Note: This user right is considered a "sensitive privilege" for the purposes of auditing.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to *S-1-5-32-544 (Administrators).
    User Rights\Modify Firmware Environment
    
    Note: Include only one User or Group per line in the Settings Catalog configuration
    screen.
  platform: windows
