apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Server (LanmanServer)' is set to 'Disabled'
  query: SELECT 1 WHERE COALESCE((SELECT UPPER(start_type) FROM services WHERE name = 'LanmanServer'), 'DISABLED') = 'DISABLED';
  critical: false
  description: "Supports file, print, and named-pipe sharing over the network for this computer. If this service is stopped, these functions will be unavailable. The recommended state for this setting is: Disabled."
  resolution: "Remediation of this service is currently not possible through Settings Catalog or a custom profile OMA-URI. Instead, it can be scripted and deployed through the Intune Scripts or Remediations blade or by other means. To establish the recommended configuration via PowerShell, run the following cmdlet: Set-Service -Name LanmanServer -StartupType Disabled"
  platform: windows
