apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'OpenSSH SSH Server (sshd)' is set to 'Disabled' or 'Not Installed'
  query: SELECT 1 WHERE COALESCE((SELECT UPPER(start_type) FROM services WHERE name = 'sshd'), 'DISABLED') = 'DISABLED';
  critical: false
  description: |
    SSH protocol based service to provide secure encrypted communications between two
    untrusted hosts over an insecure network.
    The recommended state for this setting is: Disabled or Not Installed.
    Note: This service is not installed by default. It is supplied with Windows, but it is
    installed by enabling an optional Windows feature (OpenSSH Server).
  resolution: |
    Remediation of this service is currently not possible through Settings Catalog or a
    custom profile OMA-URI. Instead, it can be scripted and deployed through the Intune
    Scripts or Remediations blade or by other means.
    To establish the recommended configuration via PowerShell, run the following cmdlet:
    Set-Service -Name sshd -StartupType Disabled
  platform: windows
