apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Turn off Push To Install service' is set to 'Enabled'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/ApplicationManagement/DisableStoreOriginatedApps</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '1';
  critical: false
  description: 'This policy setting controls whether users can push Apps to the device from the Microsoft Store App running on other devices or the web. The recommended state for this setting is: Enabled.'
  resolution: To establish the recommended configuration via configuration profiles, set the following Settings Catalog path to Enabled. Administrative Templates\Windows Components\Push to Install\Turn off Push To Install service
  platform: windows
