apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure Service 'Allow Basic authentication is set to Disabled'
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service\AllowBasic' AND data = '0';
  critical: false
  description: " This policy setting allows you to manage whether the Windows Remote Management\n(WinRM) service accepts Basic authentication from a remote client.\nThe recommended state for this setting is: Disabled."
  resolution: "\nTo establish the recommended configuration via configuration profiles, set the following\nSettings Catalog path to Disabled.\nAdministrative Templates\\Windows Components\\Windows Remote Management\n(WinRM)\\WinRM Service\\Allow Basic authentication"
  platform: windows
