apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Deny Log On As Service Job' to include 'Guests'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/UserRights/DenyLogOnAsService</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%Guests%';
  critical: false
  description: |
    This security setting determines which service accounts are prevented from registering
    a process as a service. This user right supersedes the Log on as a service user right if
    an account is subject to both policies.
    The recommended state for this setting is to include: *S-1-5-32-546 (Guests).
    Note: This security setting does not apply to the System, Local Service, or Network
    Service accounts.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to *S-1-5-32-546 (Guests).
    User Rights\Deny Log On As Service Job
  platform: windows
