apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Disable Store Originated Apps' is set to 'Enabled'
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\current\device\ApplicationManagement\DisableStoreOriginatedApps' AND data = '1';
  critical: false
  description: "This setting configures the launch of all apps from the Microsoft Store that came preinstalled or were downloaded. The recommended state for this setting is: Enabled. Note: This policy setting only applies to Windows 10 Enterprise and Windows 10 Education editions."
  resolution: "To establish the recommended configuration via configuration profiles, set the following Settings Catalog path to Enabled: Microsoft App Store\\Disable Store Originated Apps"
  platform: windows
