apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Remote Desktop Services UserMode Port Redirector (UmRdpService)' is set to 'Disabled'
  query: SELECT 1 WHERE COALESCE((SELECT UPPER(start_type) FROM services WHERE name = 'UmRdpService'), 'DISABLED') = 'DISABLED';
  critical: false
  description: 'Allows the redirection of Printers/Drives/Ports for RDP connections. The recommended state for this setting is: Disabled.'
  resolution: 'Remediation of this service is currently not possible through Settings Catalog or a custom profile OMA-URI. Instead, it can be scripted and deployed through the Intune Scripts or Remediations blade or by other means. To establish the recommended configuration via PowerShell, run the following cmdlet: Set-Service -Name UmRdpService -StartupType Disabled'
  platform: windows
