apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure System 'Specify the maximum log file size (KB) is set to Enabled and 32,768 or greater'
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\EventLog\System\MaxSize' AND CAST(data AS INTEGER) >= 32768;
  critical: false
  description: " This policy setting specifies the maximum size of the log file in kilobytes. The maximum\nlog file size can be configured between 1 megabyte (1,024 kilobytes) and 4 terabytes\n(4,194,240 kilobytes) in kilobyte increments.\nThe recommended state for this setting is: Enabled: 32,768 or greater."
  resolution: "\nTo establish the recommended configuration via configuration profiles, set the following\nSettings Catalog path to Enabled: 32,768 or greater.\nAdministrative Templates\\Windows Components\\Event Log\nService\\System\\Specify the maximum log file size (KB)."
  platform: windows
