apiVersion: v1
kind: policy
spec:
  name: 'CIS - Ensure ''Require PIN For Pairing'' is set to ''Enabled: Pairing ceremony for new devices will always require a PIN'' OR ''All pairings will require PIN'''
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/WirelessDisplay/RequirePinForPairing</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output IN ('1', '2');
  critical: false
  description: |-
    This policy setting controls whether or not a PIN is required for pairing to a wireless
    display device.
    The recommended state for this setting is: Enabled: Pairing ceremony for new
    devices will always require a PIN' OR All pairings will require PIN.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled: Pairing ceremony for new devices will
    always require a PIN' OR All pairings will require PIN.
    Administrative Templates\Network\Wireless Display\Require pin pairing
  platform: windows
