apiVersion: v1
kind: policy
spec:
  name: "CIS - Ensure 'Device Password Enabled: Alphanumeric Device Password Required' is set to 'Password or Alphanumeric PIN required'"
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\current\device\DeviceLock\AlphanumericDevicePasswordRequired' AND data = '0';
  critical: false
  description: |
    This policy setting determines the type of PIN or password this is required on a system.
    The recommended state for this setting is: Password or Alphanumeric PIN
    required.
    Note: This policy only applies if the DevicePasswordEnabled policy is set to 1. This is a
    pre-requisite for Alphanumeric Device Password Required in the settings catalog.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Password or Alphanumeric PIN required:
    Device Lock\Device Password Enabled: Alphanumeric Device Password Required
  platform: windows
