apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Disallow WinRM from storing RunAs credentials' is set to 'Enabled'
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service\DisableRunAs' AND data = '1';
  critical: false
  description: |-
    This policy setting allows you to manage whether the Windows Remote Management
    (WinRM) service will allow RunAs credentials to be stored for any plug-ins.
    The recommended state for this setting is: Enabled.
    Note: If you enable and then disable this policy setting, any values that were previously
    configured for RunAsPassword will need to be reset.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled.
    Administrative Templates\Windows Components\Windows Remote Management
    (WinRM)\WinRM Service\Disallow WinRM from storing RunAs credentials
  platform: windows
