apiVersion: v1
kind: policy
spec:
  name: 'CIS - Ensure ''Microsoft network client: Digitally sign communications (always)'' is set to ''Enabled'''
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/LocalPoliciesSecurityOptions/MicrosoftNetworkClient_DigitallySignCommunicationsAlways</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '1';
  critical: false
  description: |-
    This policy setting determines whether packet signing is required by the SMB client
    component.
    Note: When Windows Vista-based computers have this policy setting enabled and they
    connect to file or print shares on remote servers, it is important that the setting is
    synchronized with its companion setting, Microsoft network server: Digitally sign
    communications (always), on those servers. For more information about these
    settings, see the "Microsoft network client and server: Digitally sign communications
    (four related settings)" section in Chapter 5 of the Threats and Countermeasures guide.
    The recommended state for this setting is: Enabled.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled:
    Local Policies Security Options\Microsoft network client: Digitally sign
    communications (always)
  platform: windows
