apiVersion: v1
kind: policy
spec:
  name: 'CIS - Ensure ''Configure RPC listener settings: Protocols to allow for incoming RPC connections'' is set to ''Enabled: RPC over TCP'''
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/Printers/ConfigureRpcListenerPolicy</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%RpcListenerProtocols_Enum" value="5"%';
  critical: false
  description: |-
    This policy setting controls which protocols incoming Remote Procedure Call (RPC)
    connections to the print spooler are allowed to use.
    The recommended state for this setting is: Enabled: RPC over TCP.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled: RCP over TCP:
    Administrative Templates\Printers\Configure RPC listener settings: Configure
    protocol options for incoming RPC connections
  platform: windows
