apiVersion: v1
kind: policy
spec:
  name: 'CIS - Ensure ''Device Password Enabled: Max Device Password Failed Attempts'' is set to ''5 or fewer failed attempt(s), but not 0'''
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\current\device\DeviceLock\MaxDevicePasswordFailedAttempts' AND data = '5';
  critical: false
  description: |-
    This policy setting determines the number of failed logon attempts before the account is
    locked. Setting this policy to 0 does not conform to the benchmark as doing so disables
    the account lockout threshold.
    The recommended state for this setting is: 5 or fewer invalid logon attempt(s),
    but not 0.
    Note: When a user reaches the value set by this policy, the system is not wiped,
    instead the system will be in BitLocker recovery mode, which makes data inaccessible
    but recoverable. If BitLocker is not enabled, then this policy will not be enforced.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to 5 or fewer invalid logon attempt(s), but not 0:
    Device Lock\Device Password Enabled: Max Device Password Failed Attempts
  platform: windows
