apiVersion: v1
kind: policy
spec:
  name: 'CIS - Ensure ''User Account Control: Behavior of the elevation prompt for administrators'' is set to ''Prompt for consent on the secure desktop'' or higher'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/LocalPoliciesSecurityOptions/UserAccountControl_BehaviorOfTheElevationPromptForAdministrators</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '2';
  critical: false
  description: |-
    This policy setting controls the behavior of the elevation prompt for administrators.
    The recommended state for this setting is: Prompt for consent on the secure
    desktop. Configuring this setting to Prompt for credentials on the secure
    desktop also conforms to the benchmark.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Prompt for consent on the secure desktop or Prompt
    for credentials on the secure desktop:
    Local Policies Security Options\User Account Control: Behavior of the
    elevation prompt for administrators
  platform: windows
