apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Prevent enabling lock screen camera' is set to 'Enabled'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/Camera/AllowCamera</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '0';
  critical: false
  description: |-
    Disables the lock screen camera toggle switch in PC Settings and prevents a camera
    from being invoked on the lock screen.
    The recommended state for this setting is: Enabled.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled.
    Administrative Templates\Control Panel\Personalization\Prevent enabling lock
    screen camera
  platform: windows
