apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Profile System Performance' is set to 'Administrators, NT SERVICE\WdiServiceHost'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/UserRights/ProfileSystemPerformance</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%Administrators%';
  critical: false
  description: |
    This policy setting allows users to use tools to view the performance of different system
    processes, which could be abused to allow attackers to determine a system's active
    processes and provide insight into the potential attack surface of the computer.
    The recommended state for this setting is: *S-1-5-32-544, *S-1-5-80
    (Administrators, NT SERVICE\WdiServiceHost).
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to *S-1-5-32-544, *S-1-5-80 (Administrators, NT
    SERVICE\WdiServiceHost).
    User Rights\Profile System Performance
  platform: windows
