apiVersion: v1
kind: policy
spec:
  name: 'CIS - Ensure ''Device Password Enabled: Min Device Password Length'' is set to ''14 or more character(s)'''
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\current\device\DeviceLock\MinDevicePasswordLength' AND data = '14';
  critical: false
  description: |-
    This policy setting determines the least number of characters that make up a password
    for a local user account. There are many different theories about how to determine the
    best password length for an organization, but perhaps "passphrase" is a better term
    than "password." In Microsoft Windows 2000 or newer, passphrases can be quite long
    and can include spaces. Therefore, a phrase such as "I want to drink a $5 milkshake" is
    a valid passphrase; it is a considerably stronger password than an 8 or 10 character
    string of random numbers and letters, and yet is easier to remember. Users must be
    educated about the proper selection and maintenance of passwords, especially around
    password length. In enterprise environments, the ideal value for the Minimum password
    length setting is 14 characters, however you should adjust this value to meet your
    organization's business requirements.
    The recommended state for this setting is: 14 or more character(s).
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to 14 or more character(s):
    Device Lock\Device Password Enabled: Min Device Password Length
  platform: windows
