apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure Service 'Allow unencrypted traffic' is set to 'Disabled'
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service\AllowUnencryptedTraffic' AND data = '0';
  critical: false
  description: |-

    This policy setting allows you to manage whether the Windows Remote Management
    (WinRM) service sends and receives unencrypted messages over the network.
    The recommended state for this setting is: Disabled.
  resolution: |-

    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Disabled.
    Administrative Templates\Windows Components\Windows Remote Management
    (WinRM)\WinRM Service\Allow unencrypted traffic
  platform: windows
