apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Facial Features Use Enhanced Anti Spoofing' is set to 'true'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/PassportForWork/Biometrics/FacialFeaturesUseEnhancedAntiSpoofing</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = 'true';
  critical: false
  description: |-
    This policy setting determines whether enhanced anti-spoofing is configured for devices
    which support it.
    The recommended state for this setting is: true.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to true.
    Windows Hello For Business\Facial Features Use Enhanced Anti Spoofing
  platform: windows
