apiVersion: v1
kind: policy
spec:
  name: "CIS - Ensure 'Defer Quality Updates Period (Days)' is set to 'Enabled: 0 days'"
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/Update/DeferQualityUpdatesPeriodInDays</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '0';
  critical: false
  description: |
    This policy settings controls when Quality Updates are received.
    The recommended state for this setting is: Enabled: 0 days.
    Note: If the "Allow Telemetry" policy is set to 0, this policy will have no effect.
    Note #2: Starting with Windows 10 R1607, Microsoft introduced a new Windows
    Update (WU) client behavior called Dual Scan, with an eye to cloud-based update
    management. In some cases, this Dual Scan feature can interfere with Windows
    Updates from Windows Server Update Services (WSUS) and/or manual WU updates. If
    you are using WSUS in your environment, you may need to set the above setting to Not
    Configured or configure the setting Do not allow update deferral policies to cause
    scans against Windows Update (added in the Windows 10 Release 1709 Administrative
    Templates) in order to prevent the Dual Scan feature from interfering. More information
    on Dual Scan is available at these links:
    •
    •
    
    Demystifying “Dual Scan” – WSUS Product Team Blog
    Improving Dual Scan on 1607 – WSUS Product Team Blog
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled:0 days.
    Windows Update for Business\Defer Quality Updates Period (Days)
  platform: windows
