apiVersion: v1
kind: policy
spec:
  name: "CIS - Ensure 'Accounts: Enable Guest account status' is set to 'Disabled'"
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/LocalPoliciesSecurityOptions/Accounts_EnableGuestAccountStatus</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '0';
  critical: false
  description: |
    This policy setting determines whether the Guest account is enabled or disabled. The
    Guest account allows unauthenticated network users to gain access to the system.
    The recommended state for this setting is: Disabled.
    Note: This setting will have no impact when applied to the Domain Controllers
    organizational unit via group policy because Domain Controllers have no local account
    database. It can be configured at the domain level via group policy, similar to account
    lockout and password policy settings.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Disabled:
    Local Policies Security Options\Accounts: Guest account status
  platform: windows
