apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'SSDP Discovery (SSDPSRV)' is set to 'Disabled'
  query: SELECT 1 WHERE COALESCE((SELECT UPPER(start_type) FROM services WHERE name = 'SSDPSRV'), 'DISABLED') = 'DISABLED';
  critical: false
  description: |
    Discovers networked devices and services that use the SSDP discovery protocol, such
    as UPnP devices. Also announces SSDP devices and services running on the local
    computer.
    The recommended state for this setting is: Disabled.
  resolution: |
    To establish the recommended configuration, set the following Custom Configuration
    Policy to 4:
    Name:
    <Enter name>
    Description: <Enter Description>
    OMA-URI:
    ./Device/Vendor/MSFT/Policy/Config/SystemServices/ConfigureSSDPDiscoveryServi
    ceStartupMode
    Data Type:
    Integer
    Value:
    4
    
    Note: As of January 2024, despite its inclusion in Microsoft’s official documentation,
    using an OMI-URI to configure a Windows Service Startup Mode via a custom profile
    will lead to an error in Intune. This error will be logged in the local event log as “The
    system cannot find the file specified.” Currently, the most reliable method for
    remediation is through PowerShell.
    The recommended configuration can also be established via PowerShell by running the
    following cmdlet:
    Set-Service -Name SSDPSRV -StartupType Disabled
  platform: windows
