apiVersion: v1
kind: policy
spec:
  name: "CIS - Ensure 'Set the default behavior for AutoRun' is set to 'Enabled: Do not execute any autorun commands'"
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/Autoplay/SetDefaultAutoRunBehavior</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%<Enabled/>%' AND mdm_command_output LIKE '%value="1"%';
  critical: false
  description: |
    This policy setting sets the default behavior for Autorun commands. Autorun commands
    are generally stored in autorun.inf files. They often launch the installation program or
    other routines.
    The recommended state for this setting is: Enabled: Do not execute any autorun
    commands.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled: Do not execute any autorun commands.
    Administrative Templates\Windows Components\AutoPlay Policies\Set the default
    behavior for AutoRun
  platform: windows
