apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Device Password Enabled' is set to 'Enabled'
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\current\device\DeviceLock\DevicePasswordEnabled' AND data = '0';
  critical: false
  description: |-
    This policy setting specifics whether device lock is enabled. when enabled, the following
    policy settings take effect on the system which are included in the Device Lock Section:
    •
    •
    •
    •
    •
    •

    AllowSimpleDevicePassword
    MinDevicePasswordLength
    AlphanumericDevicePasswordRequired
    MaxDevicePasswordFailedAttempts
    MaxInactivityTimeDeviceLock
    MinDevicePasswordComplexCharacters

    The recommended state for this setting is: Enabled.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to `3Enabled:
    Device Lock\Device Password Enabled
  platform: windows
