apiVersion: v1
kind: policy
spec:
  name: "CIS - Ensure 'Device Password Enabled: Min Device Password Complex Characters' is set to 'Digits and lowercase letters are required'"
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\current\device\DeviceLock\MinDevicePasswordComplexCharacters' AND data LIKE '%';
  critical: false
  description: |
    This policy setting configures the number of complex element types (uppercase and
    lowercase letters, numbers, and punctuation) required for PIN or password.
    The recommended state for this setting is: Digits and lowercase letters are
    required
    Note: The enforcement of policies for Microsoft accounts happens on the server, and
    the server requires a password length of 8 and a complexity of 2. A complexity value of
    3 or 4 is unsupported and setting this value on the server makes Microsoft accounts
    non-compliant. However, configuring this setting to 2 will force the value of 3 for
    Local accounts.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Digits lowercase letters and uppercase letters are
    required:
    Device Lock\Device Password Enabled: Alphanumeric Device Password Required:
    Min Device Password Complex Characters
    
    Note: As of March 20, 2025, this setting is nested under Alphanumeric Device
    Password Required and may not fully appear in Settings Catalog unless unchecked and
    re-checked in the settings picker.
  platform: windows
