apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Prevent the use of security questions for local accounts' is set to 'Enabled'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/ADMX_CredUI/NoLocalPasswordResetQuestions</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%<enabled/>%';
  critical: false
  description: |
    This policy setting controls whether security questions can be used to reset local
    account passwords. The security question feature does not apply to domain accounts,
    only local accounts on the workstation.
    The recommended state for this setting is: Enabled.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled.
    Administrative Templates\Windows Components\Credential User Interface\Prevent
    the use of security questions for local accounts
  platform: windows
