apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Enable Sudo' is set to 'Sudo is disabled'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/Sudo/EnableSudo</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '0';
  critical: false
  description: |
    This policy setting configures the use of the sudo.exe command line tool. The sudo
    feature in Windows allows users to run elevated commands (as an administrator)
    directly from an unelevated console session.
    The recommended state for this setting is: Sudo is disabled.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Sudo is disabled.
    Sudo\Enable Sudo
  platform: windows
