apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Minimum Password Age' is set to '1 or more day(s)'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/DeviceLock/MinimumPasswordAge</LocURI></Target></Item></Get></SyncBody>' AND CAST(mdm_command_output AS INTEGER) >= 1;
  critical: false
  description: |-
    This security setting determines the period of time (in days) that a password must be
    used before the user can change it. You can set a value between 1 and 998 days, or
    you can allow changes immediately by setting the number of days to 0.
    The recommended state for this setting is: 1 or more day(s)).
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to 1 (or more day(s)):
    Device Lock\Minimum Password Age
  platform: windows
