apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Prevent enabling lock screen slide show' is set to 'Enabled'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/DeviceLock/PreventLockScreenSlideShow</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%<Enabled/>%';
  critical: false
  description: |-
    Disables the lock screen slide show settings in PC Settings and prevents a slide show
    from playing on the lock screen.
    The recommended state for this setting is: Enabled.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled.
    Administrative Templates\Control Panel\Personalization\Prevent enabling lock
    screen slide show
  platform: windows
