apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Allow scanning of all downloaded files and attachments' is set to 'Allowed'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/Defender/AllowIOAVProtection</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '1';
  critical: false
  description: |
    This policy setting configures scanning for all downloaded files and attachments.
    The recommended state for this setting is: Allowed.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Allowed.
    Defender\Allow scanning of all downloaded files and attachments
  platform: windows
