apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Allow Local Log On' is set to 'Administrators, Users'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/UserRights/AllowLocalLogOn</LocURI></Target></Item></Get></SyncBody>' AND (mdm_command_output LIKE '%Administrators%' AND mdm_command_output LIKE '%Users%');
  critical: false
  description: |-
    This policy setting determines which users can interactively log on to computers in your
    environment. Logons that are initiated by pressing the CTRL+ALT+DEL key sequence
    on the client computer keyboard require this user right. Users who attempt to log on
    through Terminal Services / Remote Desktop Services or IIS also require this user right.
    The recommended state for this setting is: *S-1-5-32-544, *S-1-5-32-545
    (Administrators, Users).
    Note: The Guest account is also assigned this user right by default. Although this
    account is disabled by default, it's recommended that you configure this setting through
    Group Policy. However, this user right should generally be restricted to the
    Administrators and Users groups. Assign this user right to the Backup Operators
    group if your organization requires that they have this capability.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to *S-1-5-32-544, *S-1-5-32-545 (Administrators, Users).
    User Rights\Allow Local Log On

    Note: Include only one User or Group per line in the Settings Catalog configuration
    screen.
  platform: windows
