apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Turn off printing over HTTP' is set to 'Enabled'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/Connectivity/DiablePrintingOverHTTP</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%<enabled%';
  critical: false
  description: 'This policy setting allows you to disable the client computer''s ability to print over HTTP, which allows the computer to print to printers on the intranet as well as the Internet. The recommended state for this setting is: Enabled. Note: This control affects printing over both HTTP and HTTPS.'
  resolution: To establish the recommended configuration via configuration profiles, set the following Settings Catalog path to Enabled. Administrative Templates\System\Internet Communication Management\Internet Communication settings\Turn off printing over HTTP
  platform: windows
