apiVersion: v1
kind: policy
spec:
  name: "CIS - Ensure 'User Account Control: Only elevate UIAccess applications that are installed in secure locations' is set to 'Enabled'"
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\EnableSecureUIAPaths' AND data = '1';
  critical: false
  description: |
    This policy setting controls whether applications that request to run with a User Interface
    Accessibility (UIAccess) integrity level must reside in a secure location in the file
    system. Secure locations are limited to the following:
    •
    •
    •
    
    …\Program Files\, including subfolders
    …\Windows\System32\
    …\Program Files (x86)\, including subfolders (for 64-bit versions of Windows)
    
    Note: Windows enforces a public key infrastructure (PKI) signature check on any
    interactive application that requests to run with a UIAccess integrity level regardless of
    the state of this security setting.
    The recommended state for this setting is: Enabled.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled:
    Local Policies Security Options\User Account Control: Only elevate UIAccess
    applications that are installed in secure locations
  platform: windows
