apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Lock Memory' is set to 'No One'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/UserRights/LockMemory</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '';
  critical: false
  description: |-
    This policy setting allows a process to keep data in physical memory, which prevents
    the system from paging the data to virtual memory on disk. If this user right is assigned,
    significant degradation of system performance can occur.
    The recommended state for this setting is: No One.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to (<![CDATA[]]>) which equals No One.
    User Rights\Lock Memory

    Note: Using (<![CDATA[]]>) to represent a blank value or No One is recommended
    by Microsoft. However, there is a known issue where an error occurs in Endpoint
    Manger (Intune) but does not affect the policy setting from being applied to the system
    properly.
  platform: windows
