apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Limit Diagnostic Log Collection' is set to 'Enabled'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/System/LimitDiagnosticLogCollection</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '1';
  critical: false
  description: |-
    This policy setting controls whether additional diagnostic logs are collected when more
    information is needed to troubleshoot a problem on the device.
    The recommended state for this setting is: Enabled.
    Note: Diagnostic logs are only sent when the device has been configured to send
    optional diagnostic data. Diagnostic data is limited when recommendation Allow
    Diagnostic Data is set to Enabled: Diagnostic data off (not recommended) or
    Enabled: Send required diagnostic data to send only basic information.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled:
    System\Limit Diagnostic Log Collection
  platform: windows
