apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Backup Directory' is set to 'Backup the password to Azure AD only'
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\LAPS\Config\BackupDirectory' AND data = '1';
  critical: false
  description: |-
    This policy setting configures which directory Windows LAPS will use to back up the
    local admin account password.
    The recommended state for this setting is: Backup the password to Azure AD only.
    Note: Organizations that utilize third-party commercial software to manage unique &
    complex local Administrator passwords on domain members may opt to disregard these
    LAPS recommendations.
    •
    •
    •

    Windows LAPS does not support standalone computers - they must be joined to
    an Active Directory domain or Entra ID (formerly Azure Active Directory).
    Windows LAPS does not support simultaneous storage of the local admin
    password in both directory types.
    If the setting is configured and the managed device is not joined to the configured
    directory type, the local administrator password will not be managed by Windows
    LAPS.

    Important: An organization wishing to use Active Directory to backup the LAPS
    password may make an exception for this recommendation. To implement Active
    Directory backup see the latest on-premises CIS Benchmark for Windows 10/11. When
    backing up with Active Directory there are 2 additional security controls to be
    considered in the benchmark which are not available when using Azure AD for backup.
    These were excluded from the Intune benchmark as they cannot be selected unless
    Active Directory is selected as the backup location.
  resolution: |-
    To establish the recommended configuration from Microsoft Intune Admin Center:
    1. Navigate to Endpoint security > Account protection.
    2. Create or edit a LAPS policy of the type Local admin password solution
    (Windows LAPS).
    3. Set Backup Directory to Backup the password to Azure AD only.
  platform: windows
