apiVersion: v1
kind: policy
spec:
  name: "CIS - Ensure 'Accounts: Limit local account use of blank passwords to console logon only' is set to 'Enabled'"
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\LimitBlankPasswordUse' AND data = '1';
  critical: false
  description: |
    This policy setting determines whether local accounts that are not password protected
    can be used to log on from locations other than the physical computer console. If you
    enable this policy setting, local accounts that have blank passwords will not be able to
    log on to the network from remote client computers. Such accounts will only be able to
    log on at the keyboard of the computer.
    The recommended state for this setting is: Enabled.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Enabled:
    Local Policies Security Options\Accounts: Limit local account use of blank
    passwords to console logon only
  platform: windows
