apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Sign-in and lock last interactive user automatically after a restart' is set to 'Disabled'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/WindowsLogon/AllowAutomaticRestartSignOn</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%<disabled/>%';
  critical: false
  description: |-
    This policy setting controls whether a device will automatically sign-in the last interactive
    user after Windows Update restarts the system.
    The recommended state for this setting is: Disabled.
  resolution: |-
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Disabled.
    Administrative Templates\Windows Components\Windows Logon Options\Sign-in and
    lock last interactive user automatically after a restart
  platform: windows
