apiVersion: v1
kind: policy
spec:
  name: 'CIS - Configure ''Accounts: Rename guest account'''
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/LocalPoliciesSecurityOptions/Accounts_RenameGuestAccount</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output NOT LIKE '%Guest%';
  critical: false
  description: The built-in local guest account is another well-known name to attackers. It is recommended to rename this account to something that does not indicate its purpose. Even if you disable this account, which is recommended, ensure that you rename it for added security.
  resolution: 'To establish the recommended configuration via configuration profiles, set the following Settings Catalog path: Local Policies Security Options\Accounts: Rename guest account'
  platform: windows
