apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Allow Realtime Monitoring' is set to 'Allowed'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/Defender/AllowRealtimeMonitoring</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '1';
  critical: false
  description: |
    This policy setting configures real-time protection prompts for known malware detection.
    Microsoft Defender Antivirus alerts you when malware or potentially unwanted software
    attempts to install itself or to run on your computer.
    The recommended state for this setting is: Allowed.
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Allowed.
    Defender\Allow Realtime Monitoring
  platform: windows
