apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Allow Telemetry' is set to 'Basic'
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/System/AllowTelemetry</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '1';
  critical: false
  description: |
    This policy setting determines the amount of diagnostic and usage data reported to
    Microsoft:
    The recommended state for this setting is: Basic or Security.
    Note: If your organization relies on Windows Update, the minimum recommended
    setting is Required diagnostic data. Because no Windows Update information is
    collected when diagnostic data is off, important information about update failures is not
    sent. Microsoft uses this information to fix the causes of those failures and improve the
    quality of updates.
    Note #2: The Configure diagnostic data opt-in settings user interface group policy can
    be used to prevent end users from changing their data collection settings.
    Note #3: Enhanced diagnostic data setting is not available on Windows 11 and
    Windows Server 2022 and has been replaced with policies that can control the amount
    of optional diagnostic data that is sent. For more information on these settings visit
    Manage diagnostic data using Group Policy and MDM
  resolution: |
    To establish the recommended configuration via configuration profiles, set the following
    Settings Catalog path to Basic or Security:
    System\Allow Telemetry
  platform: windows
