apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure iCloud Drive Document and Desktop Sync Is Disabled (MDM Required)
  query: |
    SELECT 1 WHERE 
      EXISTS (
        SELECT 1 FROM managed_policies WHERE 
            domain='com.apple.applicationaccess' AND 
            name='allowCloudDesktopAndDocuments' AND 
            (value = 0 OR value = 'false')
        )
      AND NOT EXISTS (
        SELECT 1 FROM managed_policies WHERE 
            domain='com.apple.applicationaccess' AND 
            name='allowCloudDesktopAndDocuments' AND 
            (value != 0 AND value != 'false')
        );  
  critical: false
  description: Automated Document synchronization should be planned and controlled to approved storage.
  resolution: |
    The administrator should configure this via MDM profile.
    Ask your administrator to deploy a profile with the following configuration:
      1. The PayloadType string is com.apple.applicationaccess.
      2. The key to include is allowCloudDesktopAndDocuments.
      3. The key must be set to <false/>.
  platform: darwin
