apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure Password Account Lockout Threshold Is Configured (Fleetd required)
  query: SELECT 1 FROM  pwd_policy where max_failed_attempts <= 5;
  critical: false
  description: The account lockout threshold specifies the amount of times a user can enter an incorrect password before a lockout will occur.
  resolution: |
    Automated method:
    Ask your system administrator to deploy an MDM profile that Ensure Password Account Lockout Threshold.
    Profile Method:
    Ask your administrator to deploy a profile with the following configuration:
      1. The PayloadType string is com.apple.mobiledevice.passwordpolicy 
      2. The key to include is maxFailedAttempts
      3. The key must be set to <integer><value≤5></integer>
  platform: darwin
