apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure iCloud Passwords & Keychain is enabled (if your org policy is to enable it) (MDM Required)
  query: "SELECT 1 WHERE \n  EXISTS (\n    SELECT 1 FROM managed_policies WHERE \n        domain='com.apple.applicationaccess' AND \n        name='allowCloudKeychainSync' AND \n        (value = 1 OR value = 'true')\n    )\n  AND NOT EXISTS (\n    SELECT 1 FROM managed_policies WHERE \n        domain='com.apple.applicationaccess' AND \n        name='allowCloudKeychainSync' AND \n        (value != 1 AND value != 'true')\n    );  \n/*CIS does not make a hard recommendation for this policy. Fleet has provided two policies (one failing, one succeeding). \n  Depending on your organization's decision, you can delete this policy or its counterpart.*/\n"
  critical: false
  description: |
    The iCloud Passwords & Keychain is Apple's synchronization service that works with Apple Accounts to synchronize password, passkey, and credit card information across macOS, iOS, iPadOS. The capability allows users to use synced password, passkey, and credit card information in either macOS, iOS, or iPadOS for use in Safari and other applications.
    The password, passkey, and credit card information stored on macOS in the keychain is stored in Apple's cloud, including on an Enterprise-managed computer.
    When using personal Apple Accounts, credentials may include both enterprise-related and personal data, depending on user behavior and account usage patterns.
    Rationale:
    Ensure that iCloud Passwords and Keychain usage aligns with organizational requirements, taking into account whether personal or managed Apple Accounts are being utilized.
    Impact:
    When iCloud Passwords & Keychain is enabled, password, passkey, and credit card information are synchronized across devices signed in with the same Apple Account. This may result in those items being stored in Apple's cloud and accessible across the user's Apple devices and applications that use iCloud Keychain.
  resolution: |
    The administrator should configure this via MDM profile.
    Ask your administrator to deploy a profile with the following configuration:
      1. The PayloadType string is com.apple.applicationaccess.
      2. The key to include is allowCloudKeychainSync.
      3. The key must be set to <true/>.
  platform: darwin
