apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Always install with elevated privileges' is set to 'Disabled' (User Configuration)
  query: SELECT 1 FROM registry WHERE (path LIKE 'HKEY_USERS\%\Software\Policies\Microsoft\Windows\Installer\AlwaysInstallElevated' AND data = 0);
  critical: false
  description: |
    This setting controls whether or not Windows Installer should use system permissions when it installs any program on the system.
    Note: This setting appears both in the Computer Configuration and User Configuration folders. To make this setting effective, you must enable the setting in both folders.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Disabled:
    'User Configuration\Policies\Administrative Templates\Windows Components\Windows Installer\Always install with elevated privileges'
    Note: This Group Policy path is provided by the Group Policy template MSI.admx/adml thatis included with all versions of the Microsoft Windows Administrative Templates.
  platform: windows
