apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Post-authentication actions: Actions' is set to 'Enabled: Reset the password and logoff the managed account' or higher 
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\LAPS\PostAuthenticationActions' AND data in (3,5));
  critical: false
  description: |
    This policy settings configures post-authentication actions which will be executed after detecting an authentication by the LAPS managed account. The Action refers to actions to take upon expiry of the grace period before executing the specified post- authentication actions.
    Post-authentication actions:
    • Reset password: upon expiry of the grace period, the managed account password will be reset.
    • Reset the password and logoff the managed account: upon expiry of the grace period, the managed account password will be reset and any interactive logon sessions using the managed account will terminated.
    • Reset the password and reboot the device: upon expiry of the grace period, the managed account password will be reset and the managed device will be immediately rebooted.
    Warning: After an interactive logon session is terminated, other authenticated sessions using the Windows LAPS managed account may still be active. The only way to ensure that the previous password is no longer in use is to reboot the OS.
    The recommended state for this setting is: Enabled: Reset the password and logoff the managed account or higher.
    Note: Organizations that utilize third-party commercial software to manage unique & complex local Administrator passwords on domain members may opt to disregard these LAPS recommendations.
    Note #2: Windows LAPS does not support standalone computers - they must be joined to an Active Directory domain or Entra ID (formerly Azure Active Directory).
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Enabled: Reset the password and logoff the managed account or higher:
    'Computer Configuration\Policies\Administrative Templates\System\LAPS\Post- authentication actions: Actions'
  platform: windows
