apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Password must meet complexity requirements' is set to 'Enabled'
  query: SELECT 1 FROM security_profile_info WHERE password_complexity = 1;
  critical: false
  description: |
    This policy setting checks all new passwords to ensure that they meet basic requirements for
    strong passwords. Passwords that contain only alphanumeric characters are extremely easy to
    discover with several publicly available tools.
  resolution: |
    Automatic method:
    Ask your system administrator to establish the recommended configuration via GP, set the following UI path to 'Enabled':
    'Computer Configuration\Policies\Windows Settings\Security Settings\Account Policies\Password Policy\Password must meet complexity requirements'
  platform: windows
