apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Allow Clipboard synchronization across devices' is set to 'Disabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\AllowCrossDeviceClipboard' AND data = 0);
  critical: false
  description: This setting determines whether Clipboard contents can be synchronized across devices.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Disabled:
    'Computer Configuration\Policies\Administrative Templates\System\OS Policies\Allow Clipboard synchronization across devices'
  platform: windows
