apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Allow indexing of encrypted files' is set to 'Disabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\\AllowIndexingEncryptedStoresOrItems' AND data = 0);
  critical: false
  description: This policy setting controls whether encrypted items are allowed to be indexed.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to 'Disabled':
    'Computer Configuration\Policies\Administrative Templates\Windows Components\Search\Allow indexing of encrypted files'
  platform: windows
