apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Maximum password age' is set to '365 or fewer days, but not 0'
  query: SELECT 1 FROM security_profile_info WHERE (maximum_password_age <= 365 AND maximum_password_age != 0);
  critical: false
  description: This policy setting defines how long a user can use their password before it expires.
  resolution: |
    Automatic method:
    Ask your system administrator to establish the recommended configuration via GP, set the following UI path to 365 or fewer days, but not 0:
    'Computer Configuration\Policies\Windows Settings\Security Settings\Account Policies\Password Policy\Maximum password age'
  platform: windows
