apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Relax minimum password length limits' is set to 'Enabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\SAM\\RelaxMinimumPasswordLengthLimits' AND data != 0);
  critical: false
  description: This policy setting determines whether the minimum password length setting can be increased beyond the legacy limit of 14 characters.
  resolution: |
    Automatic method:
    Ask your system administrator to establish the recommended configuration via GP, set the following UI path to 'Enabled':
    'Computer Configuration\Policies\Windows Settings\Security Settings\Account Policies\Password Policy\Relax minimum password length limits'
  platform: windows
