apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Allow remote server management through WinRM' is set to 'Disabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service\\AllowAutoConfig' AND data = 0);
  critical: false
  description: |
    This policy setting allows you to manage whether the Windows Remote Management (WinRM) service
    automatically listens on the network for requests on the HTTP transport over the default HTTP
    port.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to 'Disabled':
    'Computer Configuration\Policies\Administrative Templates\Windows Components\Windows Remote Management (WinRM)\WinRM Service\Allow remote server management through WinRM'
  platform: windows
