apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Configure SAM change password RPC methods policy' is set to 'Enabled: Block all change password RPC methods'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\SAM\SamrChangeUserPasswordApiPolicy' AND data = 1);
  critical: false
  description: |
    This policy setting determines which RPC methods can be used to change passwords stored in the Security Account Manager (SAM).
    The recommended state for this setting is: 'Enabled: Block all change password RPC methods'.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to 'Enabled: Block all change password RPC methods':
    'Computer Configuration\Policies\Administrative Templates\System\Security Account Manager\Configure SAM change password RPC methods policy'
    Note: This Group Policy path is provided by the Group Policy template 'SAM.admx/adml'
    that is included with the Microsoft Windows 11 Release 24H2 Administrative Templates (or newer).
  platform: windows
