apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Network access: Restrict anonymous access to Named Pipes and Shares' is set to 'Enabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters\restrictnullsessaccess' and data == '1');
  critical: false
  description: |
    When enabled, this policy setting restricts anonymous access to only those shares and
    pipes that are named in the Network access: Named pipes that can be accessed
    anonymously and Network access: Shares that can be accessed anonymously settings.
    This policy setting controls null session access to shares on your computers by adding
    RestrictNullSessAccess with the value 1 in the
    HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
    registry key. This registry value toggles null session shares on or off to control whether the
    server service restricts unauthenticated clients' access to named resources.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Enabled:
    'Computer Configuration\Policies\Windows Settings\Security Settings\Local Policies\Security Options\Network access: Restrict anonymous access to Named Pipes and Shares'
  platform: windows
