apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Audit Security State Change' is set to include 'Success'
  query: |
    SELECT 1 FROM mdm_bridge where mdm_command_input = "<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/Audit/System_AuditSecurityStateChange</LocURI></Target></Item></Get></SyncBody>" 
    AND (mdm_command_output = 3 OR mdm_command_output = 1);
  critical: false
  description: |
    This subcategory reports changes in security state of the system, such as when the security subsystem starts and stops. Events for this subcategory include:
    -  4608: Windows is starting up.
    -  4609: Windows is shutting down.
    -  4616: The system time was changed.
    -  4621: Administrator recovered system from CrashOnAuditFail. Users who are not
    administrators will now be allowed to log on. Some audit-able activity might not have been recorded.
    The recommended state for this setting is to include: 'Success'.
  resolution: |
    Automatic method:
    Ask your system administrator to establish the recommended configuration via GP, set the following UI path to include Success:
    'Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\System\Audit Security State Change'
  platform: windows
