apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Set authentication rate limiter delay (milliseconds)' is set to 'Enabled: 2000' or more
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LanmanServer\InvalidAuthenticationDelayTimeInMs' AND data >= 2000);
  critical: false
  description: |
    This policy settings configures the SMB server invalid authentication delay value in milliseconds.
    The recommended state for this setting is: 'Enabled: 2000' or more.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to 'Enabled: 2000' or more:
    'Computer Configuration\Policies\Administrative Templates\Network\Lanman Server\Set authentication rate limiter delay (milliseconds)'
    Note: This Group Policy path may not exist by default. It is provided by the Group Policy
    template 'LanmanServer.admx/adml' that is included with the Microsoft Windows 11 Release 24H2 Administrative Templates (or newer).
  platform: windows
