apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Network access: Sharing and security model for local accounts' is set to 'Classic - local users authenticate as themselves'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Lsa\forceguest' AND data == 0);
  critical: false
  description: |
    This policy setting determines how network logons that use local accounts are
    authenticated. The Classic option allows precise control over access to resources, including
    the ability to assign different types of access to different users for the same resource. The
    Guest only option allows you to treat all users equally. In this context, all users authenticate
    as Guest only to receive the same access level to a given resource.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Classic -
    local users authenticate as themselves:
    'Computer Configuration\Policies\Windows Settings\Security Settings\Local Policies\Security Options\Network access: Sharing and security model for local accounts'
  platform: windows
