apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Enable remote mailslots' (Lanman Server) is set to 'Disabled'
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Bowser\EnableMailslots' AND data = 0;
  critical: false
  description: This policy settings controls whether the SMB server will use remote mailslots over the computer browser service. The remote mailslots protocol is an old, simple, unreliable, and insecure inter-process communication method.
  resolution: |
    Automatic method:
    Ask your system administrator to establish the recommended configuration via GP, set the following UI path to Disabled:
    'Computer Configuration\Policies\Administrative Templates\Network\Lanman Server\Enable remote mailslots'
  platform: windows
