apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Continue experiences on this device' is set to 'Disabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\EnableCdp' AND data = 0);
  critical: false
  description: This policy setting determines whether the Windows device is allowed to participate in cross-device experiences (continue experiences).
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Disabled:
    'Computer Configuration\Policies\Administrative Templates\System\Group Policy\Continue experiences on this device'
    Note: This Group Policy path may not exist by default. It is provided by the Group Policy template GroupPolicy.admx/adml that is included with the Microsoft Windows 8.0 & Server 2012 (non-R2) Administrative Templates (or newer).
  platform: windows
