apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Configure security policy processing: Do not apply during periodic background processing' is set to 'Enabled: FALSE'
  query: SELECT 1 FROM registry WHERE path LIKE 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Group Policy\{%}\NoGPOListChanges' AND data = '0';
  critical: false
  description: |
    The "Do not apply during periodic background processing" option prevents the system from updating affected security policies in the background while the computer is in use. When background updates are disabled, updates to security policies will not take effect until the next user logon or system restart.
    This setting affects all policy settings that use the built-in security template of Group Policy (e.g. Windows Settings\Security Settings).
    The recommended state for this setting is: Enabled: FALSE (unchecked).
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Enabled, then set the Do not apply during periodic background processing option to FALSE (unchecked), then set the Process even if the group policies have not changed option to TRUE (checked):
    'Computer Configuration\Policies\Administrative Templates\System\Group Policy\Configure security policy processing'
  platform: windows
