apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Turn off Windows Customer Experience Improvement Program' is set to 'Enabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\SQMClient\\Windows\CEIPEnable' AND data = 0);
  critical: false
  description: |
    This policy setting specifies whether Windows Messenger can collect anonymous information about how the Windows Messenger software and service is used.
    Microsoft uses information collected through the Windows Customer Experience Improvement Program to detect software flaws so that they can be corrected more quickly, enabling this setting will reduce the amount of data Microsoft is able to gather for this purpose.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Enabled:
    'Computer Configuration\Policies\Administrative Templates\System\Internet Communication Management\Internet Communication settings\Turn off Windows Customer Experience Improvement Program'
  platform: windows
