apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Maximum machine account password age' is set to '30 or fewer days, but not 0'
  query: |
    SELECT 1 FROM registry WHERE
      path = 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters\MaximumPasswordAge'
    AND data <= 30 AND data != 0;
  critical: false
  description: |
    This policy setting determines the maximum allowable age for a computer account password. By
    default, domain members automatically change their domain passwords every 30 days. If you
    increase this interval significantly so that the computers no longer change their passwords, an
    attacker would have more time to undertake a brute force attack against one of the computer
    accounts.
    In Active Directory-based domains, each computer has an account and password just like every
    user. By default, the domain members automatically change their domain password every 30 days.
    If you increase this interval significantly, or set it to 0 so that the computers no longer
    change their passwords, an attacker will have more time to undertake a brute force attack to
    guess the password of one or more computer accounts.
  resolution: |
    Automatic method:
    Ask your system administrator to establish the recommended configuration via GP, set the
    following UI path to 30 or fewer days, but not 0:
    'Computer Configuration\Policies\Windows Settings\Security Settings\Local Policies\Security Options\Domain member: Maximum machine account password age'
  platform: windows
