apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Infrared monitor service (irmon)' is set to 'Disabled' or 'Not Installed'
  query: |
    SELECT 1 WHERE 
    NOT EXISTS ( SELECT 1 FROM registry WHERE key = 'HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\irmon\\Start' )
    OR 
    EXISTS ( SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\irmon\\Start' AND data == 4 );
  critical: false
  description: |
    Detects other Infrared devices that are in range and launches the file transfer application.
    The recommended state for this setting is: Disabled or Not Installed.
  resolution: |
    Automatic method:
    Ask your system administrator to establish the recommended configuration via domain GP, set the following UI path to Disabled or Not Installed.:
    'Computer Configuration\Policies\Windows Settings\Security Settings\System Services\Infrared monitor service'
  platform: windows
