apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Problem Reports and Solutions Control Panel Support (wercplsupport)' is set to 'Disabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\wercplsupport\\Start' AND data == 4);
  critical: false
  description: |
    This service provides support for viewing, sending and deletion of system-level problem reports for the Problem Reports and Solutions control panel.
    The recommended state for this setting is: Disabled.
  resolution: |
    Automatic method:
    Ask your system administrator to establish the recommended configuration via domain GP, set the following UI path to 'Disabled':
    'Computer Configuration\Policies\Windows Settings\Security Settings\System Services\Problem Reports and Solutions Control Panel Support'
  platform: windows
