- name: CIS - Ensure Complex Password Must Contain Special Character Is Configured (MDM Required)
  platform: darwin
  description: |
    Complex passwords contain one character from each of the following classes: English uppercase letters, English lowercase letters, Westernized Arabic numerals, and non- alphanumeric characters. Ensure that a special character is part of the password policy on the computer.
  resolution: |
    Ask your system administrator to deploy an MDM profile that ensures Complex Password Must Contain Special Characters
  query: "SELECT 1 WHERE \n  EXISTS (\n    SELECT 1 FROM managed_policies WHERE \n        domain='com.apple.mobiledevice.passwordpolicy' AND \n        name='minComplexChars' AND \n        value >= 1\n    )\n  AND NOT EXISTS (\n    SELECT 1 FROM managed_policies WHERE \n        domain='com.apple.mobiledevice.passwordpolicy' AND \n        name='minComplexChars' AND \n        value < 1\n    );  \n"
