apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Enable insecure guest logons' is set to 'Disabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LanmanWorkstation\AllowInsecureGuestAuth' AND data = 0);
  critical: false
  description: |
    This policy setting determines if the SMB client will allow insecure guest logons to an SMB server.
    The recommended state for this setting is: Disabled.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Disabled:
    'Computer Configuration\Policies\Administrative Templates\Network\Lanman Workstation\Enable insecure guest logons'
  platform: windows
