apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Password Settings: Password Age (Days)' is set to 'Enabled: 30 or fewer'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\LAPS\PasswordAgeDays' AND data = 30);
  critical: false
  description: |
    This policy setting configures the Windows LAPS Password Settings policy for password length.
    Each additional character in a password increases its complexity exponentially. For
    instance, a seven-character, all lower-case alphabetic password would have 26 to the
    power of 7 (approximately 8 x 10 to the power of 9 or 8 billion) possible combinations.
    At 1,000,000 attempts per second (a capability of many password-cracking utilities), it
    would only take 133 minutes to crack. A seven-character alphabetic password with case
    sensitivity has 52 to the power of 7 combinations. A seven-character case-sensitive
    alphanumeric password without punctuation has 627 combinations. An eight-character
    password has 26 to the power of 8 (or 2 x 10 to the power of 11) possible combinations.
    Although this might seem to be a large number, at 1,000,000 attempts per second it
    would take only 59 hours to try all possible passwords. Remember, these times will
    significantly increase for passwords that use ALT characters and other special keyboard
    characters such as "!" or "@". Proper use of the password settings can help make it
    difficult to mount a brute force attack.
    The recommended state for this setting is: Enabled: 30 or fewer.
    
    Note: Organizations that utilize third-party commercial software to manage unique &
    complex local Administrator passwords on domain members may opt to disregard these LAPS recommendations.
    Note 2: Windows LAPS does not support standalone computers - they must be joined
    to an Active Directory domain or Entra ID (formerly Azure Active Directory).
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Enabled, and configure the Password Age (Days) option to 30 or fewer:
    'Computer Configuration\Policies\Administrative Templates\System\LAPS\Password Settings'
    Note: This Group Policy path may not exist by default. It is provided by the Group Policy
    template 'LAPS.admx/adml' that is included with the Microsoft Windows 11 Release 22H2 Administrative Templates v3.0 (or newer).
  platform: windows
