apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Act as part of the operating system' is set to 'No One'
  query: SELECT 1 FROM mdm_bridge where mdm_command_input = "<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Config/UserRights/ActAsPartOfTheOperatingSystem</LocURI></Target></Item></Get></SyncBody>" AND mdm_command_output = "";
  critical: false
  description: |
    This policy setting allows a process to assume the identity of any user and thus gain access to the resources that the user is authorized to access.
    The recommended state for this setting is: No One.
    Note: This user right is considered a "sensitive privilege" for the purposes of auditing.
  resolution: |
    Automatic method:
    Ask your system administrator to establish the recommended configuration via GP, set the following UI path to an empty list of users:
    'Computer Configuration\Policies\Windows Settings\Security Settings\Local Policies\User Rights Assignment\Act as part of the operating system'
  platform: windows
