apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Turn off cloud consumer account state content' is set to 'Enabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\\Windows\\CloudContent\DisableConsumerAccountStateContent' AND data = 1);
  critical: false
  description: This policy setting determines whether cloud consumer account state content is allowed in all Windows experiences.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Enabled:
    'Computer Configuration\Policies\Administrative Templates\Windows Components\Cloud Content\Turn off cloud consumer account state content'
  platform: windows
