apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Block user from showing account details on sign-in' is set to 'Enabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\BlockUserFromShowingAccountDetailsOnSignin' AND data =  1);
  critical: false
  description: This policy prevents the user from showing account details (email address or user name) on the sign-in screen.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Enabled:
    'Computer Configuration\Policies\Administrative Templates\System\Logon\Block user from showing account details on sign-in'
  platform: windows
