apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Select when Quality Updates are received' is set to 'Enabled: 0 days'
  query: |
    SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\DeferQualityUpdates' AND data = 1)
    AND EXISTS (
      SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\DeferQualityUpdatesPeriodInDays' AND data = 0)
    );
  critical: false
  description: This settings controls when Quality Updates are received.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to 'Enabled: 0 days':
    'Computer Configuration\Policies\Administrative Templates\Windows Components\Windows Update\Windows Update for Business\Select when Quality Updates are received'
  platform: windows
