apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Prevent downloading of enclosures' is set to 'Enabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Internet Explorer\\Feeds\\DisableEnclosureDownload' AND data = 1);
  critical: false
  description: This policy setting prevents the user from having enclosures (file attachments) downloaded from an RSS feed to the user's computer.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to 'Enabled':
    'Computer Configuration\Policies\Administrative Templates\Windows Components\RSS Feeds\Prevent downloading of enclosures'
  platform: windows
