apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Allow Use of Camera' is set to 'Disabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Camera\AllowCamera' AND data = 0);
  critical: false
  description: |
    This policy setting controls whether the use of Camera devices on the machine are
    permitted.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Disabled:
    'Computer Configuration\Policies\Administrative Templates\Windows Components\Camera\Allow Use of Camera'
  platform: windows
