apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Interactive logon Don't display last signed-in' is set to 'Enabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\dontdisplaylastusername' AND data == 1);
  critical: false
  description: |
    This policy setting determines whether the account name of the last user to log on to the client
    computers in your organization will be displayed in each computer's respective Windows logon
    screen.
  resolution: |
    Automatic method:
    Ask your system administrator to establish the recommended configuration via GP, set the following UI path to 'Enabled':
    'Computer Configuration\Policies\Windows Settings\Security Settings\Local Policies\Security Options\Interactive logon: Don't display last signed-in'
  platform: windows
