apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Minimum password age' is set to '1 or more days'
  query: SELECT 1 FROM security_profile_info WHERE minimum_password_age >= 1;
  critical: false
  description: |
    This policy setting determines the number of days that you must use a password before you can
    change it. The range of values for this policy setting is between 1 and 999 days.
  resolution: |
    Automatic method:
    Ask your system administrator to establish the recommended configuration via GP, set the following UI path to 1 or more days:
    'Computer Configuration\Policies\Windows Settings\Security Settings\Account Policies\Password Policy\Minimum password age'
  platform: windows
