apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Digitally sign secure channel data (when possible)' is set to 'Enabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters\SignSecureChannel' AND data != 0);
  critical: false
  description: |
    This policy setting determines whether a domain member should attempt to negotiate whether all
    secure channel traffic that it initiates must be digitally signed. Digital signatures protect
    the traffic from being modified by anyone who captures the data as it traverses the network.
    When a computer joins a domain, a computer account is created. After it joins the domain, the
    computer uses the password for that account to create a secure channel with the Domain
    Controller for its domain every time that it restarts. Requests that are sent on the secure
    channel are authenticated—and sensitive information such as passwords are encrypted—but the
    channel is not integrity-checked, and not all information is encrypted.
  resolution: |
    Automatic method:
    Ask your system administrator to establish the recommended configuration via GP, set the
    following UI path to 'Enabled':
    'Computer Configuration\Policies\Windows Settings\Security Settings\Local Policies\Security Options\Domain member: Digitally sign secure channel data (when possible)'
  platform: windows
