apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Network access: Do not allow storage of passwords and credentials for network authentication' is set to 'Enabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Lsa\disabledomaincreds' AND data != 0);
  critical: false
  description: |
    This policy setting determines whether Credential Manager (formerly called Stored User
    Names and Passwords) saves passwords or credentials for later use when it gains domain
    authentication.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Enabled:
    'Computer Configuration\Policies\Windows Settings\Security Settings\Local Policies\Security Options\Network access: Do not allow storage of passwords and credentials for network authentication'
  platform: windows
