apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Audit Logon' is set to 'Success and Failure'
  query: SELECT 1 FROM cis_audit where item = "17.5.4" AND (regex_match(value,".*(?=.*Success)(?=.*Failure).*",0) is not null);
  critical: false
  description: |
    This subcategory reports when a user attempts to log on to the system. These events occur on the accessed computer. For interactive logons, the generation of these events occurs on the computer that is logged on to. If a network logon takes place to access a share, these events generate on the computer that hosts the accessed resource. If you configure this setting to No auditing, it is difficult or impossible to determine which user has accessed or attempted to access organization computers. Events for this subcategory include:
    - 4624: An account was successfully logged on.
    - 4625: An account failed to log on.
    - 4648: A logon was attempted using explicit credentials.
    - 4675: SIDs were filtered.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Success and Failure:
    'Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Logon/Logoff\Audit Logon'
  platform: windows
