apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Turn on Responder (RSPNDR) driver' is set to 'Disabled'
  query: SELECT 1 FROM registry WHERE (path = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD\EnableRspndr' AND data = 0);
  critical: false
  description: |
    This policy setting changes the operational behavior of the Responder network protocol driver. The Responder allows a computer to participate in Link Layer Topology Discovery requests so that it can be discovered and located on the network. It also allows a computer to participate in Quality-of-Service activities such as bandwidth estimation and network health analysis.
    The recommended state for this setting is: Disabled.
  resolution: |
    To establish the recommended configuration via GP, set the following UI path to Disabled (recommended):
    'Computer Configuration\Policies\Administrative Templates\Network\Link-Layer Topology Discovery\Turn on Responder (RSPNDR) driver'
  platform: windows
