apiVersion: v1
kind: policy
spec:
  name: CIS - Ensure 'Audit File Share' is set to 'Success and Failure'
  query: |
    SELECT 1 FROM mdm_bridge where mdm_command_input = "<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/Audit/ObjectAccess_AuditFileShare</LocURI></Target></Item></Get></SyncBody>" 
    AND mdm_command_output = 3;
  critical: false
  description: |
    This policy setting allows you to audit attempts to access a shared folder. The recommended state for this setting is: Success and Failure.
    Note: There are no system access control lists (SACLs) for shared folders. If this policy setting is enabled, access to all shared folders on the system is audited.
  resolution: |
    Automatic method:
    Ask your system administrator to establish the recommended configuration via GP, set the following UI path to Success and Failure:
    'Computer Configuration\Policies\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Object Access\Audit File Share'
  platform: windows
